import type { Metadata } from "next";
import {Radley, Carlito} from  "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";
import Footer from "@/app/component/footer";


const Radley_init = Radley({
  subsets:["latin"],
  weight:['400'],
  variable: "--font-Radley",
  style:["italic","normal"]

});
const Carlito_init = Carlito({
  subsets:["latin"],
  variable: "--font-Carlito",
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Radley_init.variable} ${Carlito_init.variable} antialiased`}
      > <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
